name: "Publish JSONIFY XML"

on: 
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NodeJS ğŸ“¦
        uses: actions/setup-node@v4
        with: 
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies ğŸ“‚
        run: npm ci
      - name: Test Package ğŸ§ª
        run: npm run test
      - name: Build Package ğŸ§±
        run: npm run build
      - name: Publish to NPM ğŸ’£
        run: npm publish --access=public
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN  }}